/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author caio.alunos
 */
public class CalcularSalario extends javax.swing.JFrame {

    /**
     * Creates new form CalcularSalario
     */
    public CalcularSalario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCinza = new javax.swing.JPanel();
        lblCalcularSalario = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblQuantidadedeAulas = new javax.swing.JLabel();
        lblnivel = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox<>();
        btbCalcular = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        cbCidade = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        txtQuantidadedeAulas = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtSalarioFinal = new javax.swing.JTextField();
        lblSalarioFinal = new javax.swing.JLabel();
        lblLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcule o Seu Salário");

        pnlCinza.setBackground(new java.awt.Color(102, 102, 102));

        lblCalcularSalario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCalcularSalario.setForeground(new java.awt.Color(0, 0, 0));
        lblCalcularSalario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalcularSalario.setText("Calcular Sálario");

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        lblQuantidadedeAulas.setBackground(new java.awt.Color(255, 255, 255));
        lblQuantidadedeAulas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblQuantidadedeAulas.setForeground(new java.awt.Color(0, 0, 0));
        lblQuantidadedeAulas.setText("Quantidade de Aulas");

        lblnivel.setBackground(new java.awt.Color(255, 255, 255));
        lblnivel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblnivel.setForeground(new java.awt.Color(0, 0, 0));
        lblnivel.setText("Nível");

        cbNivel.setBackground(new java.awt.Color(255, 255, 255));
        cbNivel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbNivel.setForeground(new java.awt.Color(0, 0, 0));
        cbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));
        cbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNivelActionPerformed(evt);
            }
        });

        btbCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btbCalcular.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btbCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btbCalcular.setText("Calcular");
        btbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCalcularActionPerformed(evt);
            }
        });

        lblEstado.setBackground(new java.awt.Color(255, 255, 255));
        lblEstado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("Estado");

        cbEstado.setBackground(new java.awt.Color(255, 255, 255));
        cbEstado.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbEstado.setForeground(new java.awt.Color(0, 0, 0));
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MG", "OFF", " " }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        cbCidade.setBackground(new java.awt.Color(255, 255, 255));
        cbCidade.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbCidade.setForeground(new java.awt.Color(0, 0, 0));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 0, 0));

        txtQuantidadedeAulas.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidadedeAulas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtQuantidadedeAulas.setForeground(new java.awt.Color(0, 0, 0));

        lblCidade.setBackground(new java.awt.Color(255, 255, 255));
        lblCidade.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 0, 0));
        lblCidade.setText("Cidade");

        txtSalarioFinal.setBackground(new java.awt.Color(255, 255, 255));
        txtSalarioFinal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSalarioFinal.setForeground(new java.awt.Color(0, 0, 0));

        lblSalarioFinal.setBackground(new java.awt.Color(255, 255, 255));
        lblSalarioFinal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSalarioFinal.setForeground(new java.awt.Color(0, 0, 0));
        lblSalarioFinal.setText("Sálario Final");

        lblLimpar.setBackground(new java.awt.Color(255, 255, 255));
        lblLimpar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblLimpar.setForeground(new java.awt.Color(0, 0, 0));
        lblLimpar.setText("Limpar");
        lblLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLimparActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-professor-90.png"))); // NOI18N

        javax.swing.GroupLayout pnlCinzaLayout = new javax.swing.GroupLayout(pnlCinza);
        pnlCinza.setLayout(pnlCinzaLayout);
        pnlCinzaLayout.setHorizontalGroup(
            pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCinzaLayout.createSequentialGroup()
                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCinzaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCinzaLayout.createSequentialGroup()
                                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(pnlCinzaLayout.createSequentialGroup()
                                .addComponent(lblQuantidadedeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtQuantidadedeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCinzaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome)
                            .addComponent(cbEstado, 0, 159, Short.MAX_VALUE)
                            .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCinzaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblCalcularSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlCinzaLayout.setVerticalGroup(
            pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCinzaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCalcularSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCinzaLayout.createSequentialGroup()
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnivel)
                            .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidadedeAulas)
                    .addGroup(pnlCinzaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtQuantidadedeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalarioFinal))))
                .addGap(44, 44, 44)
                .addGroup(pnlCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLimparActionPerformed
        // Botão Limpar
        
        txtNome.setText(null);
        txtQuantidadedeAulas.setText(null);
        txtSalarioFinal.setText(null);
        
    }//GEN-LAST:event_lblLimparActionPerformed

    private void cbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        //Se o index for selecionado
        if(cbEstado.getSelectedIndex()==0){
            
            //limpe tudo
            cbCidade.removeAllItems();
            
            //E mostre essas cidades
            cbCidade.addItem("São Paulo");
            cbCidade.addItem("Itapevi");
            cbCidade.addItem("São Roque");
        }
        else if (cbEstado.getSelectedIndex()==1){
            
            cbCidade.removeAllItems();
            
            cbCidade.addItem("Rio de Janeiro");
            cbCidade.addItem("Petrópolis");
            cbCidade.addItem("Ipanema");
        }
        else if(cbEstado.getSelectedIndex()==2){
            
            cbCidade.removeAllItems();
            
            cbCidade.addItem("Belo Horizonte");
            cbCidade.addItem("Juiz de Fora");
            cbCidade.addItem("Betim");
                    
                    
        }
        
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCalcularActionPerformed
        // Botão Calcular
        
        double a = 0;
        
        int quantidade = Integer.parseInt(txtQuantidadedeAulas.getText());
        
        if(cbNivel.getSelectedIndex()==0){
             a = quantidade*12;
        }
        else if(cbNivel.getSelectedIndex()==1){
            a = quantidade*15;
            
        }
        else if(cbNivel.getSelectedIndex()==2){
            a = quantidade*25;
        }
        
        txtSalarioFinal.setText(String.valueOf(a));
    
             
        
    }//GEN-LAST:event_btbCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCalcular;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCalcularSalario;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JButton lblLimpar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidadedeAulas;
    private javax.swing.JLabel lblSalarioFinal;
    private javax.swing.JLabel lblnivel;
    private javax.swing.JPanel pnlCinza;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidadedeAulas;
    private javax.swing.JTextField txtSalarioFinal;
    // End of variables declaration//GEN-END:variables
}
