/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author caio.alunos
 */
public class FrmEscolha extends javax.swing.JFrame {

    /**
     * Creates new form FrmEscolha
     */
    public FrmEscolha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSelecione = new javax.swing.JLabel();
        rbC = new javax.swing.JRadioButton();
        rbjava = new javax.swing.JRadioButton();
        rbphp = new javax.swing.JRadioButton();
        lblresposta = new javax.swing.JLabel();
        txtresposta = new javax.swing.JTextField();
        btnEscolher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione a Linguagem");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblSelecione.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSelecione.setForeground(new java.awt.Color(0, 0, 0));
        lblSelecione.setText("Selecione a Linguagem");

        rbC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbC);
        rbC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbC.setForeground(new java.awt.Color(0, 0, 0));
        rbC.setText("C#");

        rbjava.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbjava);
        rbjava.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbjava.setForeground(new java.awt.Color(0, 0, 0));
        rbjava.setText("Java");

        rbphp.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbphp);
        rbphp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbphp.setForeground(new java.awt.Color(0, 0, 0));
        rbphp.setText("PHP");
        rbphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbphpActionPerformed(evt);
            }
        });

        lblresposta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblresposta.setForeground(new java.awt.Color(0, 0, 0));
        lblresposta.setText("Resposta");

        txtresposta.setBackground(new java.awt.Color(255, 255, 255));
        txtresposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespostaActionPerformed(evt);
            }
        });

        btnEscolher.setBackground(new java.awt.Color(204, 204, 204));
        btnEscolher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEscolher.setForeground(new java.awt.Color(0, 0, 0));
        btnEscolher.setText("Escolher");
        btnEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbjava)
                                .addGap(49, 49, 49)
                                .addComponent(rbC)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 49, Short.MAX_VALUE)
                                .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbphp)
                        .addComponent(txtresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbjava)
                    .addComponent(rbC)
                    .addComponent(rbphp))
                .addGap(45, 45, 45)
                .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherActionPerformed

        //Botão Escolher
        
        if(rbjava.isSelected()){
            txtresposta.setText(" Java ");
        }
        else if (rbC.isSelected()){
            txtresposta.setText(" C# ");
        }
        else if (rbphp.isSelected()){
            txtresposta.setText(" PHP ");
        }
        

    }//GEN-LAST:event_btnEscolherActionPerformed

    private void txtrespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespostaActionPerformed

    private void rbphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbphpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbphpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscolher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblresposta;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbjava;
    private javax.swing.JRadioButton rbphp;
    private javax.swing.JTextField txtresposta;
    // End of variables declaration//GEN-END:variables
}
